update readme.md with developer instructions for setup front-end repo
Lambda-School-Labs/underdog-devs-fe-a pull request #8
Opened 2021-11-01 20:05 UTC by mariuscmoldovan

## Description
Update readme.md with developer instructions for setup the front-end repo and creating a .env file. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x ] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2021-11-01 20:16 UTC, kennymiesner commented on README.md
> +1. Clone the repo [front-end](https://github.com/Lambda-School-Labs/underdog-devs-fe-a) repositorie to your machine. DO NOT FORK.
Update 'repositorie' to 'repository'

2021-11-01 20:21 UTC, kennymiesner requested changes
The only thing I noticed was a spelling error on line 34. Added a comment for more clarification. Thank you for taking some time to get the README updated!

2021-11-01 20:34 UTC, iwood55 approved these changes
Necessary and insightful changes done to the README, well done.

2021-11-01 23:41 UTC, mariuscmoldovan reviewed
done

2021-11-03 17:11 UTC, tfbielawski commented on README.md
> +1. Clone the repo [front-end](https://github.com/Lambda-School-Labs/underdog-devs-fe-a) repositorie to your machine. DO NOT FORK.
Thanks!

2021-11-04 22:40 UTC, kennymiesner approved these changes

2021-11-05 17:31 UTC, merged